package com.awen.push.core.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.awen.push.core.entity.PushEntity;

import com.awen.push.core.dao.PushEntityDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pushEntityDaoConfig;

    private final PushEntityDao pushEntityDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pushEntityDaoConfig = daoConfigMap.get(PushEntityDao.class).clone();
        pushEntityDaoConfig.initIdentityScope(type);

        pushEntityDao = new PushEntityDao(pushEntityDaoConfig, this);

        registerDao(PushEntity.class, pushEntityDao);
    }
    
    public void clear() {
        pushEntityDaoConfig.clearIdentityScope();
    }

    public PushEntityDao getPushEntityDao() {
        return pushEntityDao;
    }

}
